services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.22
    # container_name: es01
    environment:
      - node.name=es01
      - cluster.name=cluster23
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      # - "ES_JAVA_OPTS=-Xms6g -Xmx6g"
    # command: ['sysctl', '-w', 'vm.max_map_count=262144']
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /usr/share/elasticsearch/data
      - ./heap23a.options:/usr/share/elasticsearch/config/jvm.options.d/heap23a.options
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    networks:
      - elasticNw23
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.22
    # container_name: es02
    environment:
      - node.name=es02
      - cluster.name=cluster23
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      # - "ES_JAVA_OPTS=-Xms6g -Xmx6g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /usr/share/elasticsearch/data
      - ./heap23b.options:/usr/share/elasticsearch/config/jvm.options.d/heap23b.options
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      # - ./sysctl.conf:/etc/sysctl.conf
    networks:
      - elasticNw23
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.22
    # container_name: es03
    environment:
      - node.name=es03
      - cluster.name=cluster23
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      # # set -Xms and -Xmx to the SAME value
      # # it should be 50% of your total available RAM 
      # # subject to a maximum of 31GB
      # - "ES_JAVA_OPTS=-Xms6g -Xmx6g"      ### one is Xms, another is Xmx
      # # ES_JAVA_OPTS: -Xms512m -Xmx512m       ### either use : (or) =

    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /usr/share/elasticsearch/data
      - ./heap23c.options:/usr/share/elasticsearch/config/jvm.options.d/heap23c.options
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      # - ./sysctl.conf:/etc/sysctl.conf
    networks:
      - elasticNw23

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.22
    networks:
      - elasticNw23
    ports:
      - 5601:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://es01:9200
    mem_limit: 1073741824

networks:
  elasticNw23:
    driver: bridge