services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.22
    # container_name: es01
    environment:
      - node.name=es01
      - cluster.name=cluster23
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /usr/share/elasticsearch/data
      - ./sysctl.conf:/etc/sysctl.conf
    ports:
      - 9200:9200
    networks:
      - elasticNw23
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.22
    # container_name: es02
    environment:
      - node.name=es02
      - cluster.name=cluster23
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /usr/share/elasticsearch/data
      - ./sysctl.conf:/etc/sysctl.conf
    networks:
      - elasticNw23
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.22
    # container_name: es03
    environment:
      - node.name=es03
      - cluster.name=cluster23
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"      ### one is Xms, another is Xmx
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /usr/share/elasticsearch/data
      - ./sysctl.conf:/etc/sysctl.conf
    networks:
      - elasticNw23

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.22
    networks:
      - elasticNw23
    ports:
      - 5601:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://es01:9200
    mem_limit: 1073741824

networks:
  elasticNw23:
    driver: bridge